FROM alpine as base
RUN apk update && apk add curl bash git perl make gcc musl-dev linux-headers
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN cargo install cross

FROM base as openssl
WORKDIR /app/src
COPY ./ci ./ci

FROM openssl AS openssl-1_0_1
RUN ./ci/build-openssl.sh 1_0_1

FROM openssl AS openssl-1_1_0
RUN ./ci/build-openssl.sh 1_1_0
